version: '3'
services:
  database:
    image: gvenzl/oracle-xe
    user: root
    volumes:
      - /home/oracle/oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    environment:
      - ORACLE_PASSWORD=password
