version: '3'

services:
    oracle:
        image: gvenzl/oracle-xe:21
        container_name: oracle_database
        user: root
        volumes:
          - ./oradata:/opt/oracle/oradata
        ports:
          - 1521:1521
          - 8080:8080
          - 5500:5500
        environment:
          ORACLE_PASSWORD: password

volumes:
   oradata:
